version: '3'
services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_INITDB_ARGS=--locale=C
  kwbase1:
    image: ubuntu:xenial-20170214
    command: /kwbase/kwbase start-single-node --insecure --listen-addr kwbase1
    volumes:
      - ../../../kwbase-linux-2.6.32-gnu-amd64:/kwbase/kwbase
  kwbase2:
    image: ubuntu:xenial-20170214
    command: /kwbase/kwbase start-single-node --insecure --listen-addr kwbase2
    volumes:
      - ../../../kwbase-linux-2.6.32-gnu-amd64:/kwbase/kwbase
  test:
    image: ubuntu:xenial-20170214
    # compare.test is a binary built by the pkg/compose/prepare.sh
    command: /compare/compare.test -each ${EACH} -test.run ${TESTS} -artifacts /compare
    depends_on:
      - postgres
      - kwbase1
      - kwbase2
    volumes:
      - ./compare:/compare
