version: '3'
services:
  kwbase:
    image: ubuntu:xenial-20170214
    command: /kwbase/kwbase start --insecure --listen-addr kwbase
    volumes:
      - ../../../../kwbase-linux-2.6.32-gnu-amd64:/kwbase/kwbase
  flyway:
    depends_on:
      - kwbase
    image: boxfuse/flyway:6.0.0-beta
    volumes:
      - ./sql:/sql
    command: migrate -user=root -url=jdbc:postgresql://kwbase:26257/defaultdb -locations=filesystem:/sql
