version: '3'
services:
  kdc:
    build: ./kdc
    volumes:
      - ./kdc/start.sh:/start.sh
      - keytab:/keytab
  kwbase:
    image: ubuntu:xenial-20170214
    depends_on:
      - kdc
    command: /kwbase/kwbase --certs-dir=/certs start-single-node --listen-addr kwbase
    environment:
      - KRB5_KTNAME=/keytab/kwdb.keytab
    volumes:
      - ../../.localcluster.certs:/certs
      - keytab:/keytab
      - ../../../../kwbase-linux-2.6.32-gnu-amd64:/kwbase/kwbase
  psql:
    build: ./psql
    depends_on:
      - kwbase
    environment:
      - PGHOST=kwbase
      - PGPORT=26257
      - PGSSLCERT=/certs/node.crt
      - PGSSLKEY=/certs/node.key
    volumes:
      - ./kdc/krb5.conf:/etc/krb5.conf
      - ./psql/gss_test.go:/test/gss_test.go
      - ./psql/start.sh:/start.sh
      - ../../.localcluster.certs:/certs
volumes:
  keytab:
